name: kana_listening
description: An app that randomly draws Japanese vocabularies from N5 to N1 level to test your listening, providing pronunciation and answer checking.

version: 1.0.6+23

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.6"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ">=2.3.0"
  flutter_tts: ">=4.2.0"
  cupertino_icons: ">=1.0.8"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ">=0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/data/n5_to_n1_words.json

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon-no-alpha.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/icon-no-alpha.png"
  adaptive_icon_foreground: "assets/launcher/icon-no-alpha.png"
